### ISSUE TITLE
Java data type does not map equally to SQL data type.

### ISSUE THREAD

**Issue by dannelmlj** [batavia-orm/batavia#48]
**Product**
BataviaORM

**Status**
Pending

**Describe the bug (Actual Behaviour)**
Comparing the same data type from the data source scanner does not pass the equality check with the database scanner. This is caused by different data type name in Java and SQL (e.g: string in Java, varchar in SQL)

**Expected Behaviour**
Comparing the same data type should pass equality check.

**Severity**
High

**To Reproduce**
1. Go to comparator.java
2. Prepare a data source file that has the same data type in the same table with the database
3. Add a logging message on isTypeSame

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Java Version 20.0.1
 - Database  Postgres 15

**Reporter**
Dannel 

**Assigned To:**
Enryl

**Comment by enryleinhard** [comment]
The linked PR resolves this issue. This is resolved by adding a new mapper from Java types to SQL types
